services:
  db:
    container_name: poll_db
    image: postgres:13-alpine3.14
    environment:
      POSTGRES_DB: poll
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./../docker/volumes/poll_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    container_name: poll
    image: poll
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"